services:
  mysql-server:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password123!
      MYSQL_DATABASE: ucrypt
      MYSQL_USER: admin
      MYSQL_PASSWORD: Password123!
    ports:
      - "3307:3306"
    networks:
      - uCryptNetwork

  frontend:
    image: sleepsleep1000/frontend:latest
    restart: always
    ports:
      - "80:80"
    networks:
      - uCryptNetwork
    depends_on:
      - ucrypt-app

  ucrypt-app:
    image: sleepsleep1000/backend:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3307/ucrypt
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: Password123!
      SPRING_PROFILES_ACTIVE: dev,docker
      BASIC_FOLDER_PATH: /data
    volumes:
      - data-volume:/data
    networks:
      - uCryptNetwork
    depends_on:
      - mysql-server

volumes:
  data-volume:

networks:
  uCryptNetwork:
    driver: bridge
